default:
	g++ -g -Wall -c crash.cpp
	g++ -g -Wall -c finalStates.cpp
	g++ -g -Wall -c inputAlphabet.cpp
	g++ -g -Wall -c state.cpp
	g++ -g -Wall -c tape.cpp
	g++ -g -Wall -c tapeAlphabet.cpp
	g++ -g -Wall -c transition.cpp
	g++ -g -Wall -c transitionFunction.cpp
	g++ -g -Wall -c turingMachine.cpp
	g++ -g -Wall -o tm main.cpp crash.o finalStates.o inputAlphabet.o state.o tape.o tapeAlphabet.o transition.o transitionFunction.o turingMachine.o
